port = 8001
horizon = "https://horizon-testnet.stellar.org"
network_passphrase = "Test SDF Network ; September 2015"
api_key = ""
assets = ["USD", "EUR"]

[database]
type = "mysql"
url = "root:@/gateway_test?parseTime=true"

[accounts]
authorizing_seed = "SDMRITVCFY6IIK6H5DXIVUOL342YFVE3VFOGVF3D7XXHGITPX4ABMYXR" # GCAW3TYUYGCNODKO4QKMD6PSH5GP3KES4GWGVFCKZ6DD6EJUDUQ77BO
issuing_seed = "SCLRUYW3QOMS63AU2IMAEXLCSK73RRL35SY5MYSFV6I63S7BFKJ4KBYF"     # GCOGCYU77DLEVYCXDQM7F32M5PCKES6VU3Z5GURF6U6OA5LFOVTRYPOX
receiving_account_id = "GAJBUSUTGTS3MAU2KP6MWJFJACDN4ZJ5YCET23U6XYZZ7WUD2OYQQUR2"

[hooks]
receive = "http://localhost:8002/receive"
error = "http://localhost:8002/error"
